### ISSUE TITLE
As of v0.11.0, `handlr-regex` no longer exposes a library

### ISSUE THREAD

**Issue by Anomalocaridid** [xdqi/bro#1]
Hi, I'm the maintainer of [handlr-regex](https://github.com/Anomalocaridid/handlr-regex), which this project uses as a dependency.

I just wanted to give you a heads-up that as of v0.11.0, `handlr-regex` is now a binary-only crate. I do not think I have any reason to yank existing versions that expose libraries, so you can still use up to v0.10.1 as a library, potentially.

To be honest, I never intended `handlr-regex` to be used by others as a library. I also do not even know the first thing about making a good library. I just needed a way to expose the internals to `cargo xtask`. However, I have found an alternative method for doing so and decided to stop exposing a library. I also did some pretty aggressive refactoring that would have most likely broken things for you anyways.

Thank you for using my crate and I sincerely apologize if this causes any inconvenience for you.

**Comment by xdqi** [comment]
Thanks for letting me know that. In fact I'm using a fork of handlr-regex.
So it doesn't really affects me.

Sincerely
